# Generated by Django 5.1.4 on 2025-01-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(blank=True, max_length=150, null=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category/')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
