# Generated by Django 5.1.4 on 2025-01-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
